# Things to change for further environments:
# - stage variable group name: dtos_ENVIRONMENT_variables
# -

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure/*

variables:
  - group: global_variable_group
  - group: development_variable_group
  - name: TF_DIRECTORY
    value: '$(System.DefaultWorkingDirectory)/infrastructure'

pool:
  vmImage: ubuntu-latest

# Development environment

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    dependsOn: []
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))

    jobs:
      - template: ../jobs/init_and_plan.yaml

  - stage: terraform_apply
    displayName: Terraform Apply
    dependsOn: [terraform_plan]
    condition: and(eq(dependencies.terraform_plan.outputs['init_and_plan.TerraformPlan.changesPresent'], 'true'), eq(variables['Build.Reason'], 'Manual'))

    jobs:
      - deployment: terraform_apply
        displayName: Terraform Apply
        environment: $(ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../jobs/init_and_apply.yaml
