---
# Parameters for pipeline
parameters:
  - name: sourceRegistry
    displayName: Source Registry
    type: string
    default: acrukscohmandev

  - name: sourceImageTag
    displayName: Source Image Tag
    type: string
    default: integration

  - name: destRegistry
    displayName: Destination Registry
    type: string
    default: acrukshubprodcohman

  - name: destImageTag
    displayName: Image Tag
    type: string
    default: preprod

trigger:
- none

variables:
  - name: why
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: pr
    ${{ elseif eq(variables['Build.Reason'], 'Manual' ) }}:
      value: manual
    ${{ elseif eq(variables['Build.Reason'], 'IndividualCI' ) }}:
      value: indivci
    ${{ else }}:
      value: other

name: $(Date:yyyyMMdd)$(Rev:.r)_$(SourceBranchName)_$(why)

stages:
- stage: stage_tag_integration
  displayName: Tag image with integration Tag

  jobs:
    # Job 1: Tag image with integration Tag
  - job: job_tag_integration
    pool:
      name: private-pool-dev-uks
    displayName: Tag image with integration Tag
    variables:
    - group: DEV_hub_backend
    steps:
    - task: AzureCLI@2
      name: tag_integration
      displayName: Tag Image with integration Tag
      inputs:
        azureSubscription: sc-dtos-hub-development
        addSpnToEnvironment: true
        failOnStandardError: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          az account set --subscription $(CORE_DEV_SUBSCRIPTION_ID)
          az acr login -n ${{ parameters.sourceRegistry }}

          # Fetch the list of repositories
          echo "Fetching repositories from ${{ parameters.sourceRegistry }}..."
          repositories=$(az acr repository list --name ${{ parameters.sourceRegistry }} --output json)

          # Loop through the image names:
          for repository in $(echo $repositories | jq -r '.[]')
          do
            # Get all images tagged with the source tag:
            echo "##[debug] Pulling $repository:nft..."

            az acr import --name ${{ parameters.sourceRegistry }} \
            --source ${{ parameters.sourceRegistry }}.azurecr.io/$repository:nft \
            --image $repository:integration \
            --force
          done

- stage: stage_copy_images
  displayName: Copy images from Dev Registry to Prod Registry

  jobs:
    # Job 1: Save image as artifact
  - job: job_pull_images
    pool:
      name: private-pool-dev-uks
    displayName: Grab image and save as artifact
    variables:
    - group: DEV_hub_backend
    steps:
    - task: AzureCLI@2
      name: pull_images
      displayName: Pull Images from ${{ parameters.sourceRegistry }}
      inputs:
        azureSubscription: sc-dtos-hub-development
        addSpnToEnvironment: true
        failOnStandardError: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          # Output the commands being run:
          # set -x

          az account set --subscription $(CORE_DEV_SUBSCRIPTION_ID)
          az acr login -n ${{ parameters.sourceRegistry }}

          # Fetch the list of repositories
          echo "##[debug] Fetching repositories from ${{ parameters.sourceRegistry }}..."
          repositories=$(az acr repository list --name ${{ parameters.sourceRegistry }} --output json)

          # Loop through the image names:
          for repository in $(echo $repositories | jq -r '.[]')
          do
            # Get all images tagged with the source tag:
            echo "##[debug] Pulling $repository:${{ parameters.sourceImageTag }}..."
            docker pull ${{ parameters.sourceRegistry }}.azurecr.io/$repository:${{ parameters.sourceImageTag }}

            # Get associated images tagged with PR number, by digest:
            # Get the digest of the image
            digest=$(az acr repository show --name ${{ parameters.sourceRegistry }} --image $repository:${{ parameters.sourceImageTag }} --query 'digest' --output tsv)

            # Get the tags of all images in the repository that match this digest
            tags=$(az acr repository show --name ${{ parameters.sourceRegistry }} --image $repository@$digest --query "tags" --output json | jq -r '.[] | select(. | startswith("pr"))')
            echo "##[debug] Tags: $tags"

            # Loop through the tags and pull the images
            for tag in $tags
            do
              echo "##[debug] Pulling $repository:$tag..."
              docker pull ${{ parameters.sourceRegistry }}.azurecr.io/$repository:$tag
            done

            # Delete the downloaded image:
            echo "##[debug] Deleting image $repository:${{ parameters.sourceImageTag }}..."
            #docker rmi -f ${{ parameters.sourceRegistry }}.azurecr.io/$repository

          done

          echo "##[debug] Showing all images:"
          echo "##[command]docker images"
          docker images

