---
# Parameters for pipeline
parameters:
  - name: sourceRegistry
    displayName: Source Registry
    type: string
    default: acrukscohmandev
  - name: sourceImageTag
    displayName: Source Image Tag
    type: string
    default: integration

  - name: destRegistry
    displayName: Destination Registry
    type: string
    default: acrukshubprodcohman
  - name: destImageTag
    displayName: Image Tag
    type: string
    default: preprod

trigger:
- none

variables:
  - name: why
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: pr
    ${{ elseif eq(variables['Build.Reason'], 'Manual' ) }}:
      value: manual
    ${{ elseif eq(variables['Build.Reason'], 'IndividualCI' ) }}:
      value: indivci
    ${{ else }}:
      value: other

name: $(Date:yyyyMMdd)$(Rev:.r)_$(SourceBranchName)_$(why)

stages:
- stage: stage_copy_images
  displayName: Copy images from Dev Registry to Prod Registry

  jobs:
    # Job 1: Save image as artifact
  - job: job_pull_images
    pool:
      name: private-pool-dev-uks
    displayName: Grab image and save as artifact
    variables:
    - group: DEV_hub_backend
    steps:
    - task: AzureCLI@2
      name: pull_images
      displayName: Pull Images from ${{ parameters.sourceRegistry }}
      env:
        SOURCE_REGISTRY: ${{ parameters.sourceRegistry }}
        SOURCE_TAG: ${{ parameters.sourceImageTag}}
      inputs:
        azureSubscription: sc-dtos-hub-development
        addSpnToEnvironment: true
        failOnStandardError: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          az account list -o table

          echo "##[debug] Using SERVICE_CONNECTION $(SERVICE_CONNECTION)..."

          az account set --subscription $(CORE_DEV_SUBSCRIPTION_ID)
          az account show -o table

          echo "##[debug] Logging in to $SOURCE_REGISTRY:"
          echo "##[command]az acr login -n $SOURCE_REGISTRY"
          az acr login -n $SOURCE_REGISTRY

          # Fetch the list of repositories
          echo "Fetching repositories from ${{ parameters.sourceRegistry }}..."
          repositories=$(az acr repository list --name ${{ parameters.sourceRegistry }} --output json)

          # Loop through the image names:
          for repository in $(echo $repositories | jq -r '.[]')
          do
            echo "##[debug] Fetching tags for $repository..."
            #tags=$(az acr repository show-tags --name ${{ parameters.sourceRegistry }} --repository $repository --output json)
            tags=${{ parameters.sourceImageTag }}
            for tag in $(echo $tags | jq -r '.[]')
            do
              echo "##[debug] Pulling $repository:$tag..."
              echo "##[command]docker pull ${{ parameters.sourceRegistry }}.azurecr.io/$repository:$tag"
              # docker pull ${{ parameters.sourceRegistry }}.azurecr.io/$repository:$tag
            done
          done
